linkedin:
  keywords: "software engineer"
  location: "Bengaluru"
  distance: 50
  f_WT:
  experience_levels: "2,3"
  easy_apply: false
  company_ids: []
  hours_old: 48
  fetch_description: true
  results_wanted: 100
  offset: 0
  delay_seconds: 2.5
  jitter_seconds: 1.5
  timeout_seconds: 12
